### ISSUE TITLE
Inaccuracy: VoiceOver on Mac understanding svgs with role=img

### ISSUE THREAD

**Issue by FayeDM** [a11yproject/a11yproject.com#1562] opened 2023-06-14 20:50 UTC
This is present in the current [checklists.json](https://github.com/a11yproject/a11yproject.com/blob/main/src/_data/checklists.json) around line 179:

```
"title": "Ensure that <code>img</code> elements with an <code>svg</code> source includes the <code>role=\"img\"</code> attribute.",
				"checkboxId": "svg-image-src",
				"wcag": "4.1.2 Name, Role, Value",
				"url": "https://www.w3.org/TR/UNDERSTANDING-WCAG20/ensure-compat-rsv.html",
				"description": "VoiceOver on macOS and iOS will not correctly convey the element as an image if <code>role=\"img\"</code> is not present."
```

I regularly test with VoiceOver on macOS and this is not accurate to my experience. I retested today after seeing this and found that VoiceOver does interpret an image with an svg source as an image.

In this screencapture you can see in the bottom left what VoiceOver is reading for this `<img>` with an svg source. It reads: "An infograph of Kanopi's 3 part CWI process of strategize, implement, learn & iterate., image". You can view this example live at [kanopi.com](https://kanopi.com). 

In addition, when using SiteImprove platform and extension, it may flag `role="img"` on an image element as an error due to redundancy.

I could not find any supporting content for or against this recommendation, but I figured I would post my experience anyway and let ya'll decide if it's time for an update.
 
<img width="1339" alt="Screencapture of VoiceOver reading an image element by its alt text and then element type." src="https://github.com/a11yproject/a11yproject.com/assets/43649632/88c42a78-76f4-429b-97c3-d5fcebc2a3d4">

**Comment by scottaohara** [comment] 2023-06-15 11:51
at the time this was written, this was _not_ inaccurate. Prior to september 2021 this was a common issue where images with svg sources were treated as "groups" - where this behavior had been around since at least mid-2018.

This was fixed in Safari 14.1.2 on macOS 11.5.2, and iOS 14.7.1.  So, likely safe to remove this, or specifically call out that if your support matrix requires you account for these platforms, then this would still be necessary to expose such images as the web author likely intends for them to be.

**Comment by ericwbailey** [comment] 2023-06-15 11:57
I'd advocate for keeping it in. Regressions on VoiceOver are frustratingly commonplace, Safari is not an evergreen browser, and Apple hardware is expensive. These all conspire to set up a situation where it might easily still be applicable, and the declaration doesn't hurt things in its current form.

**Comment by scottaohara** [comment] 2023-06-15 14:51
PRs are welcome :)

**Closed** 2023-06-16 22:13 UTC
