### ISSUE TITLE
role 'navigation' set on nav tag

### ISSUE THREAD

**Issue by ValorNaram** [a11yproject/a11yproject.com#607] opened 2018-06-14 20:34 UTC
I took a look over your website code and I saw this

    <nav role="navigation"

The spec https://www.w3.org/TR/html51/sections.html#elementdef-nav tells me not to set role `navigation` on `nav` tags.

Citation:

    Allowed ARIA role attribute values:
        'navigation' role (default - do not set) or presentation.

**Sorry for being so active**

**Comment by scottaohara** [comment] 2018-06-14 20:54
Thanks @ValorNaram 

You're correct that this should not be needed, and as a general rule to authors, they shouldn't need to add default roles to an element.

Landmarks like `nav`, `main`, and `banner` can be exceptions though, as legacy browsers don't communicate the role information of these HTML elements to screen readers, so adding the default `role` can be beneficial.

I think it'd be useful to check the analytics for the site and see where most of our traffic is coming from.  If the numbers are low enough (whatever that means) I could see default roles like this being removed.... but it's doing absolutely no harm in being there.

With that said, definitely something for us to check, but going to close this as it's not a bug, but a feature ;)

**Closed by scottaohara** 2018-06-14 20:54 UTC
