### ISSUE TITLE
Bug: Errors picked up by automated WAVE check - text contrast and empty link

### ISSUE THREAD

**Issue by ActiveB1t** [a11yproject/a11yproject.com#960] opened 2020-07-16 15:19 UTC
## Summary

Running the WAVE plugin shows not all text has sufficient contrast, and an empty link is present, these are minor issues and potentially false positives, as the site may serve as an example for others it would be great if at least all errors from automated tests are resolved.

### Expected result

Running a tool such as the WAVE plugin on Chrome shows no errors.

### Actual result

The plugin shows not all text has sufficient contrast and an empty link is present.

### Additional Information

- The color #FB37FF is used on a #FFFFFF background on the homepage.
- The color #0000EE is used on different background colors, this is potentially a false positive.
- An empty link is present on the page https://www.a11yproject.com/resources/ above "Inclusive Design Patterns".

**Comment by ericwbailey** [comment] 2020-07-22 01:43
Thanks for reporting this. We do have [documentation around known issues and false positives](https://github.com/a11yproject/a11yproject.com/wiki#false-positives), I'll continue to add to it as issues are uncovered.

While I agree with the sentiment of having no errors in a checker. I'm not sure we'd ever be able to get ahead of it—some checkers will flag workarounds that others report. Some checkers like axe also flag things specifically because its unsure and needs manual review.

I think there's value to that. What do you think about the idea of a post covering the topic of false positives, and how to handle them? I am thinking it could be good guidance for people new to auditing, who may not be aware of the nuance.

**Comment by StommePoes** [comment] 2020-12-27 09:07
ping

I assume the flashing pink is not waiting for a PR but waiting to get past some huge behind-the-scenes fight over what accessible colour could replace the pink?

**Comment by ericwbailey** [comment] 2020-12-30 18:50
This is still definitely on my radar. I could take a shot at it, but do you have any opinions on palette modification, @tatianamac?

**Comment by navitux** [comment] 2022-04-06 09:14
Hi, Is this still open? I want contribute

**Comment by navitux** [comment] 2022-04-07 17:07
> @navitux We'd love the help!

Hi, of course, sorry for the delay, I'm suddenly stuck with my current work, Could I check it after 17:00 CST today?? I'll give feedback as soon as possible

**Comment by ericwbailey** [comment] 2022-04-07 17:09
Absolutely no rush on our end. We'd much prefer people participate when they're in a safe and comfortable place to 🙂

**Comment by navitux** [comment] 2022-04-14 04:55
Hello, just to comment: I'm seeing that this WAVE (https://wave.webaim.org/) plugin does not detect errors in Chrome/Chromium but in Firefox it does, I think that is not needed a check since: It seems Chrome oriented site and the "contrast" issue is not really noticeable and is currently uniformed colored

**Comment by SaptakS** [comment] 2022-05-22 15:04
From https://github.com/a11yproject/a11yproject.com/issues/960#issuecomment-1098708506
> It seems Chrome oriented site

I don't think that's the case and a11yproject is not speciically oriented for a particular browser. So even if it throws error in Firefox we should definitely fix.

From https://github.com/a11yproject/a11yproject.com/issues/960#issue-658296956
> An empty link is present on the page https://www.a11yproject.com/resources/ above "Inclusive Design Patterns".

@ActiveB1t I can't find the empty link anymore. I tested both with WAVE (it doesn't seem to report for me either in firefox or chrome) and also manually I can't see any empty link in the source code. Maybe it got fixed while fixing some other stuff in website. Please let me know if you are still seeing the error. 

As of the pink color, I think that's related to the discussions here: https://github.com/a11yproject/a11yproject.com/issues/1008

**Comment by p2635** [comment] 2023-02-26 12:17
Is there anything outstanding on this issue? I am looking mainly for good first issues to work on.

When I run the WAVE tool on the site, there are no errors at this time. I think @SaptakS basically said the same thing above.

![image](https://user-images.githubusercontent.com/4522927/221409903-7f8247ff-52e6-4f23-ad26-1cd898a24dc8.png)

**Comment by ericwbailey** [comment] 2023-02-28 01:30
If it's doubly confirmed I am taking that at face value and closing. Thanks for your work on this, everyone.

**Closed by ericwbailey** 2023-02-28 01:30 UTC
Labels: bug, help wanted, good first issue, accessibility
